# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - play14-community(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1.1
      with:
        envkey_JWT_SECRET: ${{ secrets.ENVKEY_JWT_SECRET }}
        envkey_DATABASE_HOST: ${{ secrets.ENVKEY_DATABASE_HOST }}
        envkey_DATABASE_NAME: ${{ secrets.ENVKEY_DATABASE_NAME }}
        envkey_DATABASE_USERNAME: ${{ secrets.ENVKEY_DATABASE_USERNAME }}
        envkey_DATABASE_PASSWORD: ${{ secrets.ENVKEY_DATABASE_PASSWORD }}

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: play14-community
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4694050B9E854BDD9256D6838FD228A6 }}
        package: .

